version: '3.8'

services:
  postgres_test:
    image: postgres:16-alpine
    container_name: url-shortener-db-test
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: urlshortener_test_db
    ports:
      - '5433:5432'
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user']
      interval: 5s
      timeout: 5s
      retries: 5

  redis_test:
    image: redis:7-alpine
    container_name: url-shortener-redis-test
    restart: unless-stopped
    command: redis-server --appendonly no --requirepass test_redis_pass
    ports:
      - '6380:6379'
    tmpfs:
      - /data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
